# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('host', models.CharField(max_length=100)),
                ('cpu', models.IntegerField(default=1)),
                ('ram', models.IntegerField(default=1)),
                ('hd', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'ordering': ('price',),
            },
        ),
    ]
