# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server',
            new_name='Servidor',
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ('preco',)},
        ),
        migrations.RenameField(
            model_name='servidor',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='servidor',
            old_name='price',
            new_name='preco',
        ),
    ]
