# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servidores', '0002_auto_20160115_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='criador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
